<a href="https://colab.research.google.com/github/Mohammed-Taha20/OCR/blob/main/DEPI_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# prepare the Data

In [ ]:
import os
import random
from shutil import copyfile

# Set your paths
base_path = "/content/drive/MyDrive/DEPI_Project_Dataset/Arabic_Data"
img_folder = os.path.join(base_path, "img")
ann_folder = os.path.join(base_path, "ann")
output_folder = "/content/MIX_Data_Sample"  # Folder to save the sample

# Create output folders if they don't exist
os.makedirs(os.path.join(output_folder, "img"), exist_ok=True)
os.makedirs(os.path.join(output_folder, "ann"), exist_ok=True)

# Get list of all files (assuming matching names between img and ann)
img_files = [f for f in os.listdir(img_folder) if f.endswith(('.jpg', '.jpeg', '.png'))]
ann_files = [f.replace('.jpg', '.txt').replace('.jpeg', '.txt').replace('.png', '.txt') for f in img_files]

# Verify we have matching pairs
assert len(img_files) == len(ann_files), "Mismatch between image and annotation files"

# Randomly select 100 pairs
selected_pairs = random.sample(list(zip(img_files, ann_files)), 200)

# Copy selected files to output folder
for img_file, ann_file in selected_pairs:
    # Copy image
    src_img = os.path.join(img_folder, img_file)
    dst_img = os.path.join(output_folder, "img", img_file)
    copyfile(src_img, dst_img)

    # Copy annotation
    src_ann = os.path.join(ann_folder, ann_file)
    dst_ann = os.path.join(output_folder, "ann", ann_file)
    copyfile(src_ann, dst_ann)

print(f"Successfully copied 100 random samples to {output_folder}")

In [ ]:
import shutil

source_folder = "/content/MIX_Data_Sample"
destination_folder = "/content/drive/MyDrive/DEPI_Project_Dataset"

shutil.copytree(source_folder, os.path.join(destination_folder, "MIX_Data_Sample"), dirs_exist_ok=True)
print(f"Successfully copied the '{source_folder}' folder to '{destination_folder}'")

Successfully copied the '/content/MIX_Data_Sample' folder to '/content/drive/MyDrive/DEPI_Project_Dataset'

# EZOCR

In [ ]:
!pip install easyocr opencv-python matplotlib

Collecting easyocr
  Downloading easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (4.11.0.86)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from easyocr) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.5 in /usr/local/lib/python3.11/dist-packages (from easyocr) (0.21.0+cu124)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.11/dist-packages (from easyocr) (4.11.0.86)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from easyocr) (1.15.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from easyocr) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from easyocr) (11.2.1)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.11/dist-packages (from easyocr) (0.25.2)
Collecting python-bidi (from easyocr)
  Downloading python_bidi-0.6.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from easyocr) (6.0.2)
Requirement already satisfied: Shapely in /usr/local/lib/python3.11/dist-packages (from easyocr) (2.1.0)
Requirement already satisfied: pyclipper in /usr/local/lib/python3.11/dist-packages (from easyocr) (1.3.0.post6)
Collecting ninja (from easyocr)
  Downloading ninja-1.11.1.4-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch->easyocr)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch->easyocr)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch->easyocr)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch->easyocr)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch->easyocr)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch->easyocr)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->easyocr) (1.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.11/dist-packages (from scikit-image->easyocr) (2.37.0)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.11/dist-packages (from scikit-image->easyocr) (2025.3.30)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.11/dist-packages (from scikit-image->easyocr) (0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->easyocr) (3.0.2)
Downloading easyocr-1.7.2-py3-none-any.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 46.0 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.5 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 44.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 55.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 52.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 84.8 MB/s eta 0:00:00
Downloading ninja-1.11.1.4-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (422 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 422.8/422.8 kB 35.2 MB/s eta 0:00:00
Downloading python_bidi-0.6.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (292 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.9/292.9 kB 27.2 MB/s eta 0:00:00
Installing collected packages: python-bidi, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, ninja, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, easyocr
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed easyocr-1.7.2 ninja-1.11.1.4 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 python-bidi-0.6.6

In [ ]:
import easyocr

# Initialize the reader (you can include both Arabic and English if your data has both)
reader = easyocr.Reader(['en', 'ar'])  # Add 'ar' if you're working with Arabic

WARNING:easyocr.easyocr:Downloading detection model, please wait. This may take several minutes depending upon your network connection.

Progress: |██████████████████████████████████████████████████| 100.0% Complete

WARNING:easyocr.easyocr:Downloading recognition model, please wait. This may take several minutes depending upon your network connection.

Progress: |██████████████████████████████████████████████████| 100.0% Complete

In [ ]:
import os
import json
from glob import glob
from difflib import SequenceMatcher
import easyocr
import cv2
import matplotlib.pyplot as plt

## testing

In [ ]:

# Path to your image
image_path = '/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample/img/06ddca9d-2259-4973-bc2a-beb312330c90_date.jpg'  # Replace with your actual image path

# Load the image using OpenCV
image = cv2.imread(image_path)
if image is None:
    raise FileNotFoundError(f"Image not found at {image_path}")

# Initialize EasyOCR Reader with Arabic (and optionally English)
reader = easyocr.Reader(['ar', 'en'])  # You can adjust languages here

# Perform OCR
results = reader.readtext(image,paragraph = True,detail=0)
results
# Draw results on image
for (bbox, text) in results:
    # Get bounding box points
    top_left = tuple(map(int, bbox[0]))
    bottom_right = tuple(map(int, bbox[2]))

    # Draw rectangle
    cv2.rectangle(image, top_left, bottom_right, (0, 255, 0), 2)

    # Put detected text above the box
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(image, text, (top_left[0], top_left[1] - 10), font, 0.7, (0, 0, 255), 2, cv2.LINE_AA)
    print(text)
# Convert BGR to RGB for display
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Show the image with text
plt.figure(figsize=(10, 10))
plt.imshow(image_rgb)
plt.axis('off')
plt.title('Detected Text with EasyOCR')
plt.show()

['29.7', '4.95', 'حليب كامل الدىم 200مل']

## predicting func

In [ ]:
def predict_text(image_path):
    # Load the image using OpenCV
    image = cv2.imread(image_path)
    if image is None:
        raise FileNotFoundError(f"Image not found at {image_path}")

    # Initialize EasyOCR Reader with Arabic (and optionally English)
    reader = easyocr.Reader(['ar', 'en'])  # You can adjust languages here

    # Perform OCR
    results = reader.readtext(image,paragraph = True,detail=0)
    results = ' '.join(results)
    return results

##similarity

In [ ]:
# Helper function for text similarity
def average_similarity(ground_truths,perdicted):

    def string_similarity(a, b):
        return SequenceMatcher(None, a, b).ratio()

    # Calculate average similarity
    if perdicted:
        similarities = [string_similarity(pred, gt) for pred, gt in zip(perdicted, ground_truths)]
        average_similarity = sum(similarities) / len(similarities)
        print(f"\n✅ Average OCR similarity: {average_similarity:.2f}")
        return average_similarity
    else:
        print("\n⚠️ No valid predictions made.")
        return -1.0

##EZOCR Dict

In [ ]:
base_path = '/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample'

In [ ]:
def get_label(image_path):
    try:
        ann_path = image_path.replace('.jpg','.txt').replace('img','ann')
        with open(ann_path, 'r') as f:
            lines = f.readline()
            lines=eval(lines)
            result = ' '.join(lines)
            return result
    except FileNotFoundError:
        print(f"File not found: {ann_path}")

In [ ]:
predictions = []
data_dict={'image path':[] , 'labled':[],'predicted_ezOCR' :[],'similarities_ezOCR':[]}

for img in glob(os.path.join(base_path, 'img', '*')):

    results_text=predict_text(img)
    data_dict['image path'].append(img)
    data_dict['predicted_ezOCR'].append(results_text)
    label=get_label(img)
    print(f'predicted : {results_text}')
    print(f'label : {label}')
    data_dict['labled'].append(label)
    data_dict['similarities_ezOCR'].append(average_similarity(label,results_text))
    predictions.append(results_text)

predicted : SALE
label : SALE

✅ Average OCR similarity: 1.00
predicted : Invoice Date: 30-10-2021
label : Invoice Date: 30-10-2021

✅ Average OCR similarity: 1.00
predicted : 160 00 40 00 250 0 لننرن علرانى ارع
label : 40.00 160.00 فرخ حلوانى لنشون 0.250

✅ Average OCR similarity: 0.20
predicted : ٥٥ و 122 ,00 MasterCard
label : MasterCard 122.00

✅ Average OCR similarity: 0.00
predicted : GROSS: 368
label : GROSS: 368

✅ Average OCR similarity: 1.00
predicted : ٥٤٢٨ ٥١٤٥
label : RNED DETA

✅ Average OCR similarity: 0.11
predicted : البرن هام المرتجع يوم تلاثذية الطازجة ر ٤ ١روما لبائى ااصحا
label : الأصناف لباقى يوما ١٤ و الطازجة للأغذية يوم/ للمرتجع هام البون

✅ Average OCR similarity: 0.14
predicted : 875.00 875.00
label : 875.00 الصافي 875.00 الباقي

✅ Average OCR similarity: 0.54
predicted : bratui9
label : Gratuity :- --------------

✅ Average OCR similarity: 0.71
predicted : ٨،  ٥ ٥ المستلم
label : المستلم GARDEN

✅ Average OCR similarity: 0.07
predicted : تسجبل اضرببر 631- 296 220
label : 220 - 631 - 298 / ضريبي تسجيل

✅ Average OCR similarity: 0.08
predicted : P<EGYHANKARIOUS<<GESKA<OSAMA<MATTA<ATALLA<<<
label : P<EGYMANKARIOUS<<GESKA<OSAMA<MATTA<ATALLA<<<

✅ Average OCR similarity: 0.98
predicted : علبن نو عا - انواع
label : ٣٣ ٣٥٠ ٠.٠٩٥ انواع - ملبن/نوغا

✅ Average OCR similarity: 0.33
predicted : 0ct 28, 2021 Arkan Plaza
label : Oct 28, 2021 Arkan Plaza

✅ Average OCR similarity: 0.96
predicted : 1 »٥ ٥ ٠ ارز حبن 19،٥0 ا
label : 19.00 1 19.00 اورجين قهوة برافا

✅ Average OCR similarity: 0.04
predicted : لماندر 297603
label : 297603 : الفاتورة رقم 5 : اﻷصناف

✅ Average OCR similarity: 0.08
predicted : 8٧: 2١$ 19/10/2021  07;34PM
label : By: يوسف ePlus 19/10/2021 07:34PM

✅ Average OCR similarity: 0.07
predicted : ٥. ٦00 15.000 15.00 فروله ص
label : 15.00 15.000 1.000 ص فروله

✅ Average OCR similarity: 0.15
predicted :
label : ومن الشراء عملية إتمام عند بغلافها

⚠️ No valid predictions made.
predicted : الاجمالى ,00 16.
label : 15.00 الاجمالى

✅ Average OCR similarity: 0.00
predicted : خيوط - خردوات اكسسوارات
label : اكسسوارات - خردوات - خيوط

✅ Average OCR similarity: 0.00
predicted : 6.00 عدد الاماد
label : 6.00 الاصناف  عدد

✅ Average OCR similarity: 0.33
predicted : آناناس ) 235 ملا
label : مللي 235 أناناس

✅ Average OCR similarity: 0.07
predicted : 11.08 6.5 1.705
label : 11.08 6.5 1.705 طماطم

✅ Average OCR similarity: 1.00
predicted : المجموع الفر عى
label : ١٠٧,٠٢ الفرعي المجموع

✅ Average OCR similarity: 0.00
predicted : #  36541 ٢٧٤٢٧
label : CHECK # 36541

✅ Average OCR similarity: 0.00
predicted : 9970
label : 9970 الفاتورة

✅ Average OCR similarity: 1.00
predicted : Net Sales
label : ١٠.٤٤ Net Sales

✅ Average OCR similarity: 0.11
predicted : ا0
label : com ; المقترحات و للتعليقات

✅ Average OCR similarity: 0.00
predicted : MERIT FILTER
label : MERIT FILTER

✅ Average OCR similarity: 1.00
predicted : EGP Blue Pullover Navy 50985 Floral 69.99
label : 50985 Floral Navy Blue Pullover EGP 69.99

✅ Average OCR similarity: 0.22
predicted : Cash EGP 329.99
label : Cash EGP 329.99

✅ Average OCR similarity: 1.00
predicted :
label : مصر بنك

⚠️ No valid predictions made.
predicted : Transactic 58
label : Transactio 58

✅ Average OCR similarity: 0.92
predicted : Transactio "164
label : Transactio 164

✅ Average OCR similarity: 0.79
predicted : 0.00 جر١' 81.7!
label : 0.00 Tax 81.79

✅ Average OCR similarity: 0.36
predicted : اسو اق البركة الجارحى م
label : الجارحى البركة أسواق

✅ Average OCR similarity: 0.05
predicted : مرجان للمأكو لات البحرية
label : البحرية للمأكولات مرجان

✅ Average OCR similarity: 0.00
predicted : 622400875610
label : 622400875610

✅ Average OCR similarity: 1.00
predicted : HASTERCAID
label : MASTERCARD

✅ Average OCR similarity: 0.80
predicted : ٥٥ لقامآ آ٠ح
label : Total Due : 220.0

✅ Average OCR similarity: 0.00
predicted : 900,00
label : 900.00

✅ Average OCR similarity: 0.83
predicted : 0,00 3,76 لعمة 70 جرام
label : 7.50 0.00 2 3.75 جرام 70 لحمه اندومي

✅ Average OCR similarity: 0.14
predicted : صبدابة غااد
label : غادة .د صيدلية

✅ Average OCR similarity: 0.18
predicted : 49 58  لإجما لها عاء ذ الفطع
label : 58.49 اﻹجمالى ٤ القطع عدد

✅ Average OCR similarity: 0.04
predicted : 40. 00 جمالي
label : 40.00 الإجمالى

✅ Average OCR similarity: 0.33
predicted :
label : تصنيع عيب بها

⚠️ No valid predictions made.
predicted : 1590 01121635980
label : 01121635980 1590

✅ Average OCR similarity: 0.06
predicted : 202/؛0/')[
label : Date : 07/09/2022

✅ Average OCR similarity: 0.00
predicted : الزعت PM 08:32:40 20/1 0/2021
label : PM 08:32:40 20/10/2021: الوقت مباشر بيع

✅ Average OCR similarity: 0.14
predicted : دسانداى كارامهل
label : كاراميل صانداي

✅ Average OCR similarity: 0.14
predicted : Mobi le number 01050540740
label : Mobile number 01050540740

✅ Average OCR similarity: 0.16
predicted : لقسه ب 10/22/2021 12:36:58 PM
label : 10/22/2021 12:36:58 PM :إيصال

✅ Average OCR similarity: 0.03
predicted : 70 علبه سابليا 140.00
label : 140.00 70 2 سابليه علبه

✅ Average OCR similarity: 0.05
predicted : REFERENCE 116020000546
label : REFERENCE  116020000546

✅ Average OCR similarity: 0.64
predicted : قم التسلسلي "168
label : 168 : التسلسلي رقم

✅ Average OCR similarity: 0.06
predicted : Lucky Voucher 20 L٠E: 40.00
label : Lucky Voucher 20 L.E: 40.00

✅ Average OCR similarity: 0.96
predicted : ناربخ اللانورق : 02:?6;114M 23/10/?021
label : 23/10/2021 02:26:11AM : الفاتورة تاريخ

✅ Average OCR similarity: 0.00
predicted : 261.00
label : 261.00 الإجمالي

✅ Average OCR similarity: 1.00
predicted : تاما نكامن الددم
label : جنيه 4 الخدمة تكلفة

✅ Average OCR similarity: 0.12
predicted : الباب Doctor
label : Doctor : البائع

✅ Average OCR similarity: 0.00
predicted : 4000000004/010 A/D
label : AID : A0000000041010

✅ Average OCR similarity: 0.22
predicted : Code 1331354
label : Code 1331354

✅ Average OCR similarity: 1.00
predicted : FUTTAIH ٧٥٧ ٦٥ bg HAJJID AL Broushi
label : Brought to you by MAJID AL FUTTAIM

✅ Average OCR similarity: 0.18
predicted : 29.7 4.95 حليب كامل الدىم 200مل
label : 29.7 6 4.95 مل200 الدسم كامل حليب المراعي

✅ Average OCR similarity: 0.19
predicted : ٥٥ ٥
label : 0.00 : المتبقى

✅ Average OCR similarity: 0.00
predicted : INSIDE THE SHOP Af!D If! ^ 6OOD
label : INSIDE THE SHOP AND IN A GOOD

✅ Average OCR similarity: 0.62
predicted : Discount
label : Discount

✅ Average OCR similarity: 1.00
predicted : Iransaction #: 3084284
label : Transaction #: 3084284

✅ Average OCR similarity: 0.95
predicted : 15260 NuIber : ١١٥ ١»١ ٥١ ١
label : HotLine Number: 15260

✅ Average OCR similarity: 0.00
predicted : A(/I#:001414 0000008!216'/ ٨٨
label : RRN : 000000892167 AUTH : 001414

✅ Average OCR similarity: 0.07
predicted : Company Name: ترب الفرت من الإيداع رالم
label : Company Name: الافريقى العربي البنك الإيداع/السحب من الغرض *

✅ Average OCR similarity: 0.41
predicted : PROMO   LIGHTER
label : PROMO LIGHTER

✅ Average OCR similarity: 0.46
predicted : 12;35 A٢ 9/18/2022
label : 12:35 AM 9/18/2022

✅ Average OCR similarity: 0.89
predicted : '1`٣`4٨8; 93
label : Trans : 93

✅ Average OCR similarity: 0.00
predicted : اكسريس مادكت
label : ماركت اكسبريس

✅ Average OCR similarity: 0.00
predicted : CHIP ONLINE
label : CHIP  ONLINE

✅ Average OCR similarity: 0.45
predicted :
label : 8683112785250 1 349.00 349.00

⚠️ No valid predictions made.
predicted : THU & FRI 9 AM to 1O:30 PM
label : THU & FRI 9 AM to 10:30 PM

✅ Average OCR similarity: 0.96
predicted : 80120
label : 80120

✅ Average OCR similarity: 1.00
predicted : لمطلواب ;
label : ج ١٥,٠٠ :المطلوب

✅ Average OCR similarity: 0.11
predicted : 544900022083
label : 544900022083

✅ Average OCR similarity: 1.00
predicted : بمل ا خ بالورن ث ) اذسع مما
label : شرائح بالوزن بطارخ رومى جبنه

✅ Average OCR similarity: 0.11
predicted : Order#
label : Order#

✅ Average OCR similarity: 1.00
predicted : مجموع
label : :مجموع

✅ Average OCR similarity: 0.00
predicted : Card Tax 100-403-085
label : Tax Card : 100-403-085

✅ Average OCR similarity: 0.10
predicted : عملبس مذبواه
label : مقبولة عملية

✅ Average OCR similarity: 0.00
predicted : 99.00 99 00
label : 99.00 99.00 دبل سوبر عربي فراخ 1

✅ Average OCR similarity: 0.91
predicted : 03
label : Lucky Hd3

✅ Average OCR similarity: 0.00
predicted : Hini Hawawshi 75.00 L٤
label : 1 Mini Hawawshi 75.00 LE

✅ Average OCR similarity: 0.14
predicted : ميلكا بار تريبل شوكليت
label : شوكليت تريبل  بار  ميلكا

✅ Average OCR similarity: 0.09
predicted : المدفو ٤ 99.00
label : 99.00 :المدفوع

✅ Average OCR similarity: 0.00
predicted : 0سم 4 آ عم3 ن زاا
label : الشراء تاريخ غضون 14 يوما من

✅ Average OCR similarity: 0.00
predicted : 00 201 ذقدئ
label : 201.00 :نقدي

✅ Average OCR similarity: 0.25
predicted : الإجمالب ولرت للار فل الكمية المنف
label : وفرت الاجمالي بعد قبل الكمية الصنف

✅ Average OCR similarity: 0.47
predicted : 515v4:01ذ 765:1 0a٥t:47"1
label : Store:501 POS:3 User:4797

✅ Average OCR similarity: 0.28
predicted : ديه 93
label : 93 ورديه

✅ Average OCR similarity: 0.00
predicted : 5 EGP Cash 75
label : 75 EGP Cash

✅ Average OCR similarity: 0.00
predicted : Black/ local
label : Black/local

✅ Average OCR similarity: 0.55
predicted : 8 0 75 1 receipt : Sales
label : Sales receipt : 80751

✅ Average OCR similarity: 0.00
predicted : خدمة غيارزيت
label : زيت غيار خدمة

✅ Average OCR similarity: 0.00
predicted : اجمالى السعر الكميا الوحدة الآسم
label : السعر إجمالى الكمية الوحدة اﻹسم

✅ Average OCR similarity: 0.52
predicted : Total After DneLuun , 300
label : Total After Discount: 300

✅ Average OCR similarity: 0.76
predicted : 10.00 000 10.00 المر اعى امل
label : 10.00 1.000 10.00 ٤٤٠مل المراعى رايب

✅ Average OCR similarity: 0.32
predicted : ٧ ٦١١ ٨٥١٠ ٩ ١
label : ١٩٨٥/٠٩/١٧ ٢ ٨٥ ٠٩ ١٧ ٢١ ٠٠١ ٧٧

✅ Average OCR similarity: 0.21
predicted : 40071754 ٢05 00
label : POS ID : 40021354

✅ Average OCR similarity: 0.13
predicted : $A1056000055168 ايصال
label : SA1056000055168 :إيصال

✅ Average OCR similarity: 0.71
predicted : مملمه المراء دمرىىة سايمال
label : بايصال ومرفقة الشراء عملية

✅ Average OCR similarity: 0.08
predicted : دقم اذتورة 360210 التاريخ 2022/09/22 20.51
label : 20.51 2022/09/22 : التاريخ 360210 : الفاتورة رقم

✅ Average OCR similarity: 0.02
predicted :
label : ف مشروب

⚠️ No valid predictions made.
predicted : 35700005
label : 35700005

✅ Average OCR similarity: 1.00
predicted : ابع المنطئه الصناعبة الثائبه بجوار كونكربت
label : كونكريت بجوار الثانبة الصناعية المنطقه روائع

✅ Average OCR similarity: 0.02
predicted : الشكاوى  والمقترحات
label : المقترحات و الشكاوى

✅ Average OCR similarity: 0.11
predicted : المبما السدر الددا ال دمرف
label : القيمة السعر الكمية الصنف

✅ Average OCR similarity: 0.44
predicted : الباقى 0
label : 0 : الباقي

✅ Average OCR similarity: 0.00
predicted : ذبنراك مر ب: برنتال ابن جم 220
label : 220 جم رايب برتقال مربي فيتراك

✅ Average OCR similarity: 0.13
predicted : RKET
label : RKET

✅ Average OCR similarity: 1.00
predicted : ٨٧٥٨٦٤٧» ٢١٨ ٥٢٧١
label : OFFLINE PIN VALIDATED

✅ Average OCR similarity: 0.00
predicted : 191589020 0I0:
label : MID : 1691589020

✅ Average OCR similarity: 0.00
predicted : ٦ * ٦٨ ,al Wlaclragab com ٢٧٥٢٦٦٠ * » ؛» ٨ ؛»
label : ***** www.awladragab.com ****

✅ Average OCR similarity: 0.10
predicted :
label : ١٥٧-١٦٧ ملح مقرمشات ميكس

⚠️ No valid predictions made.
predicted : ;  190195
label : 190195 : س.ت

✅ Average OCR similarity: 0.22
predicted : 0% عذ با ا دمر وذن
label : 0% وزن احمر عنب

✅ Average OCR similarity: 0.27
predicted : عاا الفنة الصنف إجمالى
label : إجمالى الفئة عدد الصنف

✅ Average OCR similarity: 0.00
predicted : 0)18[{;1 I0N؟:
label : DIRECTIONS :

✅ Average OCR similarity: 0.00
predicted : 40019196 POS ID
label : POS ID : 40019196

✅ Average OCR similarity: 0.07
predicted : !78  801a
label : 278 Bola

✅ Average OCR similarity: 0.38
predicted : 91n  Hiker 150 Hitch ؟7 .65
label : Hitoh Hiker 150 gm. 1 65.75

✅ Average OCR similarity: 0.07
predicted : Facebook Inistagram
label : Facebook  Instagram

✅ Average OCR similarity: 0.84
predicted : 15,54 عذب اببالانلديل كر
label : ١كي تصدير ابيض عنب 15.54

✅ Average OCR similarity: 0.17
predicted : 6224061105005 )/.90 (0،00)
label : 37.90 (6.00) 2 6224001105005

✅ Average OCR similarity: 0.12
predicted : 12.00/27.00
label : 12.00/27.00

✅ Average OCR similarity: 1.00
predicted : عمل
label : عمر

✅ Average OCR similarity: 0.67
predicted : ١ ٦٨٢٥٤٤
label : info@el -

✅ Average OCR similarity: 0.00
predicted : حدمة الموصيل الاحمالى
label : التوصيل خدمة اﻷجمالى

✅ Average OCR similarity: 0.15
predicted : ٠٦ ٦ ؟ البقائة التبميل المجمدات
label : التجميل و البقالة و المجمدات

✅ Average OCR similarity: 0.04
predicted : 0 لإجتلى دىة رصنا
label : 0 الاجمالى 0 توصيل خدمة

✅ Average OCR similarity: 0.18
predicted : Ta٨ ) 1101أ Take-Out Total 10. 00
label : Take-out Total (incl Tax) 10.00

✅ Average OCR similarity: 0.13
predicted : '1'1`48 : 9
label : Trans : 9

✅ Average OCR similarity: 0.11
predicted : Delivery
label : Delivery

✅ Average OCR similarity: 1.00
predicted : وزن تدصا ت كا جر سا
label : وزن ساده كاجو محمصات

✅ Average OCR similarity: 0.37
predicted :
label : 622300565034

⚠️ No valid predictions made.
predicted : ائق ا لا مر
label : جيزه - الاهرام حدائق

✅ Average OCR similarity: 0.09
predicted : Items Total 57. 89
label : Total Items 1 57.89

✅ Average OCR similarity: 0.11
predicted : Sales VAT 4.91
label : Sales VAT 4.91

✅ Average OCR similarity: 1.00
predicted : CHECK
label : CHECK

✅ Average OCR similarity: 1.00
predicted : Pico Sweet Corn 3Dc
label : Pico Sweet Corn 3pc

✅ Average OCR similarity: 0.95
predicted : 10059
label : 10059 رقم

✅ Average OCR similarity: 1.00
predicted : 251.25 الاجم
label : 251.25 اﻹجمالى

✅ Average OCR similarity: 0.67
predicted : شيكولات
label : شيكولات

✅ Average OCR similarity: 1.00
predicted : 341.0
label : 341.0 خصم

✅ Average OCR similarity: 1.00
predicted : إفتتاح فرع الرحاب الفاهر
label : القاهرة الرحاب فرع إفتتاح تم

✅ Average OCR similarity: 0.04
predicted : Net=69.81 Ent=13.96 |Add=2 04 Vat =4.19
label : Net=69.81 |Ent=13.96 | Add=2.04 |Vat=4.19

✅ Average OCR similarity: 0.26
predicted : ٧ 1٧ 17 , 50 Change
label : Change 17.50

✅ Average OCR similarity: 0.17
predicted :
label : احمد على ابو

⚠️ No valid predictions made.
predicted :
label : 10.08 خصم

⚠️ No valid predictions made.
predicted : 3.65 4.95 تروبيكانا غتبر جو اذر 235
label : 3.65 1 4.95 235 جوافه عصير تروبيكانا بيتي

✅ Average OCR similarity: 0.17
predicted : 00 با ل 7.00
label : .21 1.030 7.00 بال سايب فريش جزر

✅ Average OCR similarity: 0.00
predicted : L٠٤ الصافى 28.00
label : L.E 28.00 : الصافى

✅ Average OCR similarity: 0.12
predicted : تمم 5٤ ٣،
label : الفاتوره اجمالى : 37.50

✅ Average OCR similarity: 0.00
predicted : 8 ٢ S٤RVED H٩L AL M٥H٨M٤٥
label : SERVED BY : MOHAMED HALAL

✅ Average OCR similarity: 0.08
predicted : مومه كممم
label : MASTER

✅ Average OCR similarity: 0.00
predicted :
label : الشبكات في البطأ عند

⚠️ No valid predictions made.
predicted :
label : القيمة السعر كمية

⚠️ No valid predictions made.
predicted : 3. 74-
label : 3.74-

✅ Average OCR similarity: 0.40
predicted : Haather Gr٥y , لل
label : M , Grey Heather

✅ Average OCR similarity: 0.00
predicted : ٤٧ ٧١ Cal/ o /ostival ٨/ C
label : KFC - Cairo Festival City

✅ Average OCR similarity: 0.12
predicted : Sub Total 145
label : Sub Total 145

✅ Average OCR similarity: 1.00
predicted : 350. 00L.٤ الجزني
label : 350.00L.E الجزئي

✅ Average OCR similarity: 0.31
predicted : 3? P٢ 2/ 061 202/ 3'
label : 27 Oct 2021 at 7:32 PM

✅ Average OCR similarity: 0.05
predicted : 19 0 19
label : 19 0 19

✅ Average OCR similarity: 1.00
predicted : جعالي 40,00 اعبة 3,00000 عءد الأصناف 2
label : 40.00 : الإجمالي 3.00000 : كمية 2 : الاصناف عدد

✅ Average OCR similarity: 0.24
predicted :
label : -5.70 خصم

⚠️ No valid predictions made.
predicted : T،،x ١ ١٧ ٧ ١١
label : Tax 0.00

✅ Average OCR similarity: 0.12
predicted :
label : ٠١٠١٧٤٧١٤٦٠ - ٠١١١٩٥٠٢٠٩٩ -: الدليفرى دمة

⚠️ No valid predictions made.
predicted :
label : القيمة السعر الكمية الصنف

⚠️ No valid predictions made.
predicted : ذلك
label : قيمة وذلك

✅ Average OCR similarity: 0.00
predicted : 30031-129919 NU٥P٢٠ ReCeIDt
label : Receipt Number: 30031-129919

✅ Average OCR similarity: 0.00
predicted : (VAT -Inclusive) Sublotal
label : Subtotal  (VAT-Inclusive)

✅ Average OCR similarity: 0.00
predicted :  ١ ٧؛9 11/00/? ٨٥٢0 ١
label : Date: 11/09/22 9:04

✅ Average OCR similarity: 0.11
predicted :
label : العميل

⚠️ No valid predictions made.
predicted : For comp laints and SU9geSUTOnS
label : For complaints and suggestion

✅ Average OCR similarity: 0.28
predicted : Printed 4t: 2022/09/18 09"28:29 PM
label : Printed At: 2022/09/18 09:28:29 PM

✅ Average OCR similarity: 0.94
predicted : N10 Order 6629212 1440
label : Order No : 6629212 - 1440

✅ Average OCR similarity: 0.05
predicted : 9.50 الا جمالى
label : 9.50 الاجمالى

✅ Average OCR similarity: 0.62
predicted : 2;17;34PM 15/10/2021 Created
label : Created  : 15/10/2021 2:17:34 PM

✅ Average OCR similarity: 0.00
predicted : Change 0.00
label : Change 0.00

✅ Average OCR similarity: 1.00
predicted : اكياس نفايانا
label : نفايات اكياس - فور

✅ Average OCR similarity: 0.15
predicted : *GASOLINE 92 ٤GP   440 ,00
label : *GASOLINE 92 1 EGP 440.00

✅ Average OCR similarity: 0.72
predicted : 207#8
label : 20TAB

✅ Average OCR similarity: 0.40
predicted :  (4!{ L٢P/  110.0000
label : Credit Card 110.0000

✅ Average OCR similarity: 0.45
predicted : 1١ ٠ ١0 البانى :
label : 11.10 : الباقى

✅ Average OCR similarity: 0.50
predicted : 10/05/232:
label : 10/06/2021

✅ Average OCR similarity: 0.70
predicted : 57.14 EGP المبلغ الكلي :
label : 57.14 EGP :الكلي المبلغ

✅ Average OCR similarity: 0.61
predicted : 749 بون
label : 749 : رقم بون

✅ Average OCR similarity: 0.57
predicted : SubTotal L٤38, 00
label : SubTotal LE38.00

✅ Average OCR similarity: 0.81
predicted : AHOUNT 90 L_E518
label : AMOUNT  LE518.50

✅ Average OCR similarity: 0.38
predicted : 106 Store ٢0$: 1 U8er: 335
label : Store : 106 poS : 1 User : 335

✅ Average OCR similarity: 0.00
predicted :
label : 304.21 الخصم قبل الفاتوره اجمالى

⚠️ No valid predictions made.
predicted : Sub Total /2.00
label : Sub Total 72.00

✅ Average OCR similarity: 0.93

## ensure images type

In [ ]:
import os

folder_path = '/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample/img'  # Replace with your folder path
all_files = os.listdir(folder_path)

file_types = set()
for file in all_files:
    _, extension = os.path.splitext(file)
    if extension:
        file_types.add(extension.lower())

print("File types in the folder:")
for type in file_types:
    print(type)

File types in the folder:
.jpg

In [ ]:
del type

## CSV file

In [ ]:
import pandas as pd

df=pd.DataFrame(data_dict,columns=data_dict.keys())
df.head()

,image path,labled,predicted_ezOCR,similarities_ezOCR
0,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,SALE,SALE,1.0
1,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,Invoice Date: 30-10-2021,Invoice Date: 30-10-2021,1.0
2,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,40.00 160.00 فرخ حلوانى لنشون 0.250,160 00 40 00 250 0 لننرن علرانى ارع,0.2
3,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,MasterCard 122.00,"٥٥ و 122 ,00 MasterCard",0.0
4,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,GROSS: 368,GROSS: 368,1.0

In [ ]:
df.to_csv('/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample/EZ_OCR.csv')

# ***tesseract***

In [ ]:
!sudo apt install tesseract-ocr libtesseract-dev tesseract-ocr-ara tesseract-ocr-eng
!pip install pytesseract opencv-python easyocr arabic-reshaper python-bidi matplotlib

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
tesseract-ocr-eng is already the newest version (1:4.00~git30-7274cfa-1.1).
tesseract-ocr-eng set to manually installed.
The following NEW packages will be installed:
  libarchive-dev libleptonica-dev libtesseract-dev tesseract-ocr-ara
0 upgraded, 4 newly installed, 0 to remove and 34 not upgraded.
Need to get 4,388 kB of archives.
After this operation, 17.4 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libarchive-dev amd64 3.6.0-1ubuntu1.4 [581 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libleptonica-dev amd64 1.82.0-3build1 [1,562 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libtesseract-dev amd64 4.1.1-2.1build1 [1,600 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-ara all 1:4.00~git30-7274cfa-1.1 [645 kB]
Fetched 4,388 kB in 2s (2,838 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 4.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libarchive-dev:amd64.
(Reading database ... 126101 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.6.0-1ubuntu1.4_amd64.deb ...
Unpacking libarchive-dev:amd64 (3.6.0-1ubuntu1.4) ...
Selecting previously unselected package libleptonica-dev.
Preparing to unpack .../libleptonica-dev_1.82.0-3build1_amd64.deb ...
Unpacking libleptonica-dev (1.82.0-3build1) ...
Selecting previously unselected package libtesseract-dev:amd64.
Preparing to unpack .../libtesseract-dev_4.1.1-2.1build1_amd64.deb ...
Unpacking libtesseract-dev:amd64 (4.1.1-2.1build1) ...
Selecting previously unselected package tesseract-ocr-ara.
Preparing to unpack .../tesseract-ocr-ara_1%3a4.00~git30-7274cfa-1.1_all.deb ...
Unpacking tesseract-ocr-ara (1:4.00~git30-7274cfa-1.1) ...
Setting up tesseract-ocr-ara (1:4.00~git30-7274cfa-1.1) ...
Setting up libleptonica-dev (1.82.0-3build1) ...
Setting up libarchive-dev:amd64 (3.6.0-1ubuntu1.4) ...
Setting up libtesseract-dev:amd64 (4.1.1-2.1build1) ...
Processing triggers for man-db (2.10.2-1) ...
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (4.11.0.86)
Collecting easyocr
  Downloading easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Collecting arabic-reshaper
  Downloading arabic_reshaper-3.0.0-py3-none-any.whl.metadata (12 kB)
Collecting python-bidi
  Downloading python_bidi-0.6.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from pytesseract) (24.2)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from pytesseract) (11.2.1)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.11/dist-packages (from opencv-python) (2.0.2)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from easyocr) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.5 in /usr/local/lib/python3.11/dist-packages (from easyocr) (0.21.0+cu124)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.11/dist-packages (from easyocr) (4.11.0.86)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from easyocr) (1.15.2)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.11/dist-packages (from easyocr) (0.25.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from easyocr) (6.0.2)
Requirement already satisfied: Shapely in /usr/local/lib/python3.11/dist-packages (from easyocr) (2.1.0)
Collecting pyclipper (from easyocr)
  Downloading pyclipper-1.3.0.post6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting ninja (from easyocr)
  Downloading ninja-1.11.1.4-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch->easyocr)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch->easyocr)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch->easyocr)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch->easyocr)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch->easyocr)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch->easyocr)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch->easyocr)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->easyocr) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->easyocr) (1.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.11/dist-packages (from scikit-image->easyocr) (2.37.0)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.11/dist-packages (from scikit-image->easyocr) (2025.3.30)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.11/dist-packages (from scikit-image->easyocr) (0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->easyocr) (3.0.2)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Downloading easyocr-1.7.2-py3-none-any.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 44.0 MB/s eta 0:00:00
Downloading arabic_reshaper-3.0.0-py3-none-any.whl (20 kB)
Downloading python_bidi-0.6.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (292 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.9/292.9 kB 20.8 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 102.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 79.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 3.0 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 65.2 MB/s eta 0:00:00
Downloading ninja-1.11.1.4-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (422 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 422.8/422.8 kB 20.9 MB/s eta 0:00:00
Downloading pyclipper-1.3.0.post6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (969 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 969.6/969.6 kB 34.3 MB/s eta 0:00:00
Installing collected packages: python-bidi, pyclipper, arabic-reshaper, pytesseract, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, ninja, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, easyocr
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed arabic-reshaper-3.0.0 easyocr-1.7.2 ninja-1.11.1.4 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 pyclipper-1.3.0.post6 pytesseract-0.3.13 python-bidi-0.6.6

In [ ]:
# Step 2: Import libraries
import pytesseract

import cv2
import numpy as np
from PIL import Image
from google.colab.patches import cv2_imshow
from arabic_reshaper import ArabicReshaper
from bidi.algorithm import get_display
from matplotlib import pyplot as plt
import os
import json
from glob import glob
from difflib import SequenceMatcher

In [ ]:
# Step 3: Configure Tesseract (Colab specific)
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

In [ ]:
!sudo apt install tesseract-ocr-ara

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr-ara is already the newest version (1:4.00~git30-7274cfa-1.1).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.

In [ ]:
def tesseract_prediction(img_path):
    # Path to your image
    image_path = img_path # Replace this with your image path

    # Load image
    image = cv2.imread(image_path)
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Set language (eng+ara for English and Arabic)
    custom_config = r'-l eng+ara --oem 3 --psm 6'

    # OCR prediction
    text = pytesseract.image_to_string(image_rgb, config=custom_config)

    # Also print full text output
    print("Extracted Text:\n", text)
    return text

In [ ]:
base_path='/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample'

/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample/img/02da316f-9ad1-45d8-98ce-90ec9816d1ae_line_110.jpg

In [ ]:
def get_label_tesseract(image_path):
    try:
        ann_path = image_path.replace('.jpg','.txt').replace('img','ann')
        with open(ann_path, 'r') as f:
            lines = f.readline()
            lines=eval(lines)
            result = ' '.join(lines)
            return result
    except FileNotFoundError:
        print(f"File not found: {ann_path}")

In [ ]:
# Helper function for text similarity
def average_similarity_tesseract(ground_truths,perdicted):

    def string_similarity(a, b):
        return SequenceMatcher(None, a, b).ratio()

    # Calculate average similarity
    if perdicted:
        similarities = [string_similarity(pred, gt) for pred, gt in zip(perdicted, ground_truths)]
        average_similarity = sum(similarities) / len(similarities)
        print(f"\n✅ Average OCR similarity: {average_similarity:.2f}")
        return average_similarity
    else:
        print("\n⚠️ No valid predictions made.")
        return -1.0

In [ ]:
predictions = []
data_dict={'image path':[] , 'labled':[],'predicted_tesseract' :[],'similarities_tesseract':[]}

for img in glob(os.path.join(base_path, 'img', '*')):

    results_text=tesseract_prediction(img)
    data_dict['image path'].append(img)
    data_dict['predicted_tesseract'].append(results_text)
    label=get_label_tesseract(img)
    data_dict['labled'].append(label)
    data_dict['similarities_tesseract'].append(average_similarity_tesseract(label,results_text))
    predictions.append(results_text)

Extracted Text:
 SALE


✅ Average OCR similarity: 1.00
Extracted Text:
 Invoice Date: 30-10-2021


✅ Average OCR similarity: 1.00
Extracted Text:
 0 لئنشون حلوائي فرع ;469.90 40.00


✅ Average OCR similarity: 0.00
Extracted Text:
 eee aan Oe ite
MasterCard 122.00


✅ Average OCR similarity: 0.06
Extracted Text:
 GROSS: 368


✅ Average OCR similarity: 1.00
Extracted Text:
 RED DETA


✅ Average OCR similarity: 0.11
Extracted Text:
 البون هام للمرتجع/يوع للأغذية الطازجة و 4 ١روما‏ لباقى الأصئاف


✅ Average OCR similarity: 0.08
Extracted Text:
 875.00  يفاصلا‎ eee, Meee
Oe 727 07


✅ Average OCR similarity: 0.33
Extracted Text:
 GF SCULG Seats


✅ Average OCR similarity: 0.12
Extracted Text:
 ‎GARDE‏ المستلم


✅ Average OCR similarity: 0.07
Extracted Text:
 تسجيل ضريبي / 298 - 631 - 220


✅ Average OCR similarity: 0.14
Extracted Text:
 P<EG YMANKARIOUS<<GESKA<OSAMA<MATTA<ATALLA<<<


✅ Average OCR similarity: 0.20
Extracted Text:
 ملبن/نوغا - انواع مقي ‎rr rey‏


✅ Average OCR similarity: 0.00
Extracted Text:
 Oct 28, 2021 Arkan Plaza


✅ Average OCR similarity: 1.00
Extracted Text:
 براقا قهوة أورجين 19.00 1 19.00


✅ Average OCR similarity: 0.06
Extracted Text:
 الأصستاف : 5 ركم لفاتورة : 297603


✅ Average OCR similarity: 0.03
Extracted Text:
 By ‏وررزترى يوسف‎ 19/10/2021 07:34PM


✅ Average OCR similarity: 0.15
Extracted Text:
 فروله ص 1 1.000 15.000 45.00


✅ Average OCR similarity: 0.04
Extracted Text:
 بغلافها عند إتسام عملية الث
إتسام عصلية الشترا + وس


✅ Average OCR similarity: 0.03
Extracted Text:
 ‎ee 10 ee ae‏ سسا
‎٠‏ الاجمسالىي 46.00


✅ Average OCR similarity: 0.00
Extracted Text:
 خيوط -خردوات - اكسسواراة


✅ Average OCR similarity: 0.00
Extracted Text:
 6.00 lod! sas


✅ Average OCR similarity: 0.33
Extracted Text:
 أثائاس 235 ملاى


✅ Average OCR similarity: 0.07
Extracted Text:
 طماطم 1.74% | 65 11.08


✅ Average OCR similarity: 0.10
Extracted Text:
 المجموع الفرعي ا


✅ Average OCR similarity: 0.00
Extracted Text:
 CHECK # 26541


✅ Average OCR similarity: 0.92
Extracted Text:
 9970)s . oa


✅ Average OCR similarity: 0.31
Extracted Text:
 6١44 Net Sales
‏لكو ا‎ cm ed


✅ Average OCR similarity: 0.00
Extracted Text:
 3< للتعليقات والمقترحات : ‎١017١‏


✅ Average OCR similarity: 0.07
Extracted Text:
 MERIT FILTER


✅ Average OCR similarity: 1.00
Extracted Text:
 50985 Floral Navy Blue Pullover EGP 69.99


✅ Average OCR similarity: 1.00
Extracted Text:
 Cash EGP 329.99


✅ Average OCR similarity: 1.00
Extracted Text:
 2-6 كان


✅ Average OCR similarity: 0.14
Extracted Text:
 Transactio 58


✅ Average OCR similarity: 1.00
Extracted Text:
 Transactio 164


✅ Average OCR similarity: 1.00
Extracted Text:
 0.00 | Tox 41.79


✅ Average OCR similarity: 0.36
Extracted Text:
 اسواق البركة الجارحى


✅ Average OCR similarity: 0.10
Extracted Text:
 مرجان للمأكولات البحرية


✅ Average OCR similarity: 0.00
Extracted Text:
 622400875610


✅ Average OCR similarity: 1.00
Extracted Text:
 MASTERCARD


✅ Average OCR similarity: 0.91
Extracted Text:
 7 يوي
|


✅ Average OCR similarity: 0.00
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 إندومي لحمة 70 جرام ‎ae‏ | 375 | 2 | 9.00 || 760


✅ Average OCR similarity: 0.06
Extracted Text:
 Pees oo ‏صبداية‎


✅ Average OCR similarity: 0.14
Extracted Text:
 عدد القطع 4 الإجمالى 58.49 |


✅ Average OCR similarity: 0.00
Extracted Text:
 سم صم متسس سمت مس | ‎men ba ap a‏
الإجمالى | 40.00


✅ Average OCR similarity: 0.07
Extracted Text:
 Aer) Ge) Ly


✅ Average OCR similarity: 0.00
Extracted Text:
 01121635980 EET


✅ Average OCR similarity: 0.75
Extracted Text:
 1s See gees ewe”
re OT TON] 2022


✅ Average OCR similarity: 0.06
Extracted Text:
 بيع مباشر الواقت :20/10/2021 08:32:40 ‎PM‏


✅ Average OCR similarity: 0.08
Extracted Text:
 عساند اى كارراصواق..


✅ Average OCR similarity: 0.00
Extracted Text:
 Mobile number 01050540740


✅ Average OCR similarity: 1.00
Extracted Text:
 10/22/2021 12:36:58 py 00


✅ Average OCR similarity: 0.78
Extracted Text:
 140.00 70 2 bce


✅ Average OCR similarity: 0.71
Extracted Text:
 REFERENCE «116026000546


✅ Average OCR similarity: 0.91
Extracted Text:
 168: ‏التسلسلي‎ ay


✅ Average OCR similarity: 0.61
Extracted Text:
 Lucky Voucher 20 L.E: 40.00


✅ Average OCR similarity: 1.00
Extracted Text:
 [ 0 ‏ا‎ aie ate
23/10/2021 02:26:11AM : ‏تاروم الفاتور و‎


✅ Average OCR similarity: 0.00
Extracted Text:
 261.00 aay! oe


✅ Average OCR similarity: 0.44
Extracted Text:
 ذكاعة الخدمة 4 جلهه


✅ Average OCR similarity: 0.05
Extracted Text:
 Doctor : sui |


✅ Average OCR similarity: 0.60
Extracted Text:
 AID -A0000000041010


✅ Average OCR similarity: 0.55
Extracted Text:
 (Code 1331354


✅ Average OCR similarity: 0.08
Extracted Text:
 Brousht to you by MAJID AL FUTTAIM


✅ Average OCR similarity: 0.97
Extracted Text:
 6


✅ Average OCR similarity: 0.00
Extracted Text:
 wo0.00. ‏الع‎


✅ Average OCR similarity: 0.07
Extracted Text:
 INSIDE THE SHOP AND In A Goop


✅ Average OCR similarity: 0.86
Extracted Text:
 Discount


✅ Average OCR similarity: 0.89
Extracted Text:
 | Transacti on #: 3084284


✅ Average OCR similarity: 0.18
Extracted Text:
 et inet eke
Hot bine Number: 15260


✅ Average OCR similarity: 0.10
Extracted Text:
 KK ¥ VOOQU0892Z2167 AUTH: 001414


✅ Average OCR similarity: 0.28
Extracted Text:
 EEE
Company Name: $255) 4 pal eld ERE
adkca Wee a


✅ Average OCR similarity: 0.02
Extracted Text:
 PROMO LIGHTER


✅ Average OCR similarity: 1.00
Extracted Text:
 12:35 AM 9/18/2022


✅ Average OCR similarity: 1.00
Extracted Text:
 Trans: 93


✅ Average OCR similarity: 0.50
Extracted Text:
 ارس مايا


✅ Average OCR similarity: 0.00
Extracted Text:
 ‎ONLINE‏ 77 عل رترت


✅ Average OCR similarity: 0.00
Extracted Text:
 0683112705256 1 349,00 349.00.


✅ Average OCR similarity: 0.86
Extracted Text:
 THU & FRI 9 AM to 10:30 PM


✅ Average OCR similarity: 1.00
Extracted Text:
 80120


✅ Average OCR similarity: 1.00
Extracted Text:
 Bes ‏لمطلوب.‎


✅ Average OCR similarity: 0.00
Extracted Text:
 | 544900022083


✅ Average OCR similarity: 0.08
Extracted Text:
 خبالوزن شرائج
‎Ce Giada tes ay) Liye‏


✅ Average OCR similarity: 0.07
Extracted Text:
 Order #


✅ Average OCR similarity: 0.83
Extracted Text:
 مجموع:


✅ Average OCR similarity: 0.00
Extracted Text:
 Tax Card : 100-403-085


✅ Average OCR similarity: 1.00
Extracted Text:
 aby. aslo


✅ Average OCR similarity: 0.00
Extracted Text:
 1 | فراخ عوبى سوبر دبل }99.00 | 99.00 |


✅ Average OCR similarity: 0.00
Extracted Text:
 B Lucky Hd3


✅ Average OCR similarity: 0.00
Extracted Text:
 1 Hini Hawaushi 75.00 LE


✅ Average OCR similarity: 0.92
Extracted Text:
 ميلكا بار تريبل شوكليت


✅ Average OCR similarity: 0.08
Extracted Text:
 المدفرع: 99.00 ‘


✅ Average OCR similarity: 0.00
Extracted Text:
 .: ‏أغفون‎ 7
3 famed
£4] pid | a ‏ننسا‎ qlee


✅ Average OCR similarity: 0.00
Extracted Text:
 نقدي: 201.00


✅ Average OCR similarity: 0.00
Extracted Text:
 ‎aan‏ الكمية قبل بعد الإجمالي وفرت
‎Site.‏


✅ Average OCR similarity: 0.09
Extracted Text:
 Mitore: 50) PoS:3 User: 4797


✅ Average OCR similarity: 0.00
Extracted Text:
 ورديه 93


✅ Average OCR similarity: 0.00
Extracted Text:
 75 EGP Cash


✅ Average OCR similarity: 1.00
Extracted Text:
 Black/local


✅ Average OCR similarity: 1.00
Extracted Text:
 Sales receipt: 80751


✅ Average OCR similarity: 0.62
Extracted Text:
 خدمة غيارزيت


✅ Average OCR similarity: 0.00
Extracted Text:
 al ee ee |


✅ Average OCR similarity: 0.08
Extracted Text:
 Total After Discount: 300


✅ Average OCR similarity: 1.00
Extracted Text:
 00.00 {79-000 [10.00 ff at ‏يب المراعى.‎


✅ Average OCR similarity: 0.22
Extracted Text:
 اام سو وام ‎WAY‏ :/4\0\


✅ Average OCR similarity: 0.04
Extracted Text:
 POS ID : 40021354


✅ Average OCR similarity: 1.00
Extracted Text:
 ‎a ae ee etn nan hl.‏ يدم و طقل
ليصال ‎SA1LOS6000055168 ١‏


✅ Average OCR similarity: 0.00
Extracted Text:
 عملية الشراء ومرفقة بايصال


✅ Average OCR similarity: 0.04
Extracted Text:
 —— ‏مسح‎ aa >
2051 noz2iegm22: si) 360210)» ‏رقم الخانو‎


✅ Average OCR similarity: 0.10
Extracted Text:
 bus


✅ Average OCR similarity: 0.00
Extracted Text:
 35700005


✅ Average OCR similarity: 1.00
Extracted Text:
 SSNS ‏المنطقه المرزاعية الثائب؛ رجوار‎ cots


✅ Average OCR similarity: 0.09
Extracted Text:
 الشكاوى والمفترحات


✅ Average OCR similarity: 0.16
Extracted Text:
 “learn
‏السو‎
‏الكمية‎
‏السنئف‎


✅ Average OCR similarity: 0.00
Extracted Text:
 O: ws


✅ Average OCR similarity: 0.00
Extracted Text:
 فيتراك مربي برنتقال دابن ‎pe‏ 220


✅ Average OCR similarity: 0.13
Extracted Text:
 RKET


✅ Average OCR similarity: 1.00
Extracted Text:
 OFFLINE PIN VALIDATED


✅ Average OCR similarity: 1.00
Extracted Text:
 MID: 1691589020
MID: 1691589020


✅ Average OCR similarity: 0.19
Extracted Text:
 ****% wow. awladragab.com****


✅ Average OCR similarity: 0.41
Extracted Text:
 NAV MOY gle o Ls pda ‏مركسي‎


✅ Average OCR similarity: 0.08
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 عدب أحمر وزن 0%


✅ Average OCR similarity: 0.00
Extracted Text:
 الصنف_<- | عدد | الفنة | إجمالى


✅ Average OCR similarity: 0.18
Extracted Text:
 “DIRECT LONS;


✅ Average OCR similarity: 0.00
Extracted Text:
 POS ID : 40019196


✅ Average OCR similarity: 1.00
Extracted Text:
 P78 Bola Mee os


✅ Average OCR similarity: 0.88
Extracted Text:
 Hitoh Hiker 150 gm. 14 6507 7


✅ Average OCR similarity: 0.78
Extracted Text:
 Facebook Instagram


✅ Average OCR similarity: 0.45
Extracted Text:
 4 عب اببس تصدير اكب


✅ Average OCR similarity: 0.05
Extracted Text:
 37.90 (6.00) 2 6224001105005


✅ Average OCR similarity: 1.00
Extracted Text:
 12.00/27,.00


✅ Average OCR similarity: 0.82
Extracted Text:
 عمر


✅ Average OCR similarity: 1.00
Extracted Text:
 info@el-1


✅ Average OCR similarity: 0.78
Extracted Text:
 الأإحمالى خدمة التوصيل


✅ Average OCR similarity: 0.10
Extracted Text:
 a ee ee
‏المجمدات و البقائة و التجميط‎
Cee ‏المجمدات و البقالة و‎


✅ Average OCR similarity: 0.18
Extracted Text:
 0 wel Lr fee


✅ Average OCR similarity: 0.14
Extracted Text:
 | Take-Out Total (incl Tax) 10.00


✅ Average OCR similarity: 0.03
Extracted Text:
 Trans:9


✅ Average OCR similarity: 0.56
Extracted Text:
 Delivery


✅ Average OCR similarity: 1.00
Extracted Text:
 محمصات كاجو ساده وزن


✅ Average OCR similarity: 0.00
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 حداآئق الاهرام - جيز.


✅ Average OCR similarity: 0.45
Extracted Text:
 rata Items 1 57.89


✅ Average OCR similarity: 0.11
Extracted Text:
 = a ‏سس‎ 4.91
Sales VAT


✅ Average OCR similarity: 0.00
Extracted Text:
 CHECK


✅ Average OCR similarity: 1.00
Extracted Text:
 Pico Sweet Corn 3pc_ ff


✅ Average OCR similarity: 1.00
Extracted Text:
 A. 0059 ak)


✅ Average OCR similarity: 0.00
Extracted Text:
 الأجقتلد 251.25


✅ Average OCR similarity: 0.00
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 bos LAN © ‏اقرع ازا‎ nay
eee Cc a8) ‏حم‎


✅ Average OCR similarity: 0.04
Extracted Text:
 Net=69.81 Ent=13.96 |Add=2.04 Vat=4.19


✅ Average OCR similarity: 0.25
Extracted Text:
 Chi ‏د‎ 0
| Change 17.50


✅ Average OCR similarity: 0.17
Extracted Text:
 5 2 ah
hal ee


✅ Average OCR similarity: 0.00
Extracted Text:
 10,08 ook


✅ Average OCR similarity: 0.56
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 جزر فريظ سايب بل 7.00 11030 0351


✅ Average OCR similarity: 0.03
Extracted Text:
 TE 28.00 Ara


✅ Average OCR similarity: 0.07
Extracted Text:
 37.50 < الجمانى القالوره


✅ Average OCR similarity: 0.22
Extracted Text:
 SERVED BY : MOHAMED HALAL


✅ Average OCR similarity: 1.00
Extracted Text:
 PA.
‏حييم‎ <<: 5


✅ Average OCR similarity: 0.17
Extracted Text:
 : 4
عبت و#فسييقا في الشبيريحاتكت


✅ Average OCR similarity: 0.15
Extracted Text:
 eee eee


✅ Average OCR similarity: 0.00
Extracted Text:
 3. 74=


✅ Average OCR similarity: 0.40
Extracted Text:
 M, Grey Heather


✅ Average OCR similarity: 0.06
Extracted Text:
 KFC} Cairo Festival lity


✅ Average OCR similarity: 0.12
Extracted Text:
 * Sub Total “145


✅ Average OCR similarity: 0.00
Extracted Text:
 الجزني 0:7 —


✅ Average OCR similarity: 0.00
Extracted Text:
 27 Oct 2021 at 7:32PM


✅ Average OCR similarity: 0.86
Extracted Text:
 19019


✅ Average OCR similarity: 0.29
Extracted Text:
 عدد الأصاف: 2 كمية: 3,00000 ‎١‏ 0 الإجمالي :40,00 7


✅ Average OCR similarity: 0.11
Extracted Text:
 3.70 pod


✅ Average OCR similarity: 0.00
Extracted Text:
 Ta 000


✅ Average OCR similarity: 0.38
Extracted Text:
 SP VVEV VET? -2 11090. 1s MUR pty tat) 4.5


✅ Average OCR similarity: 0.02
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 وذلك قيمة


✅ Average OCR similarity: 0.11
Extracted Text:
 Receipt Number: 3nn1-129919


✅ Average OCR similarity: 0.64
Extracted Text:
 SubTotal (VAT-Inclusive) 68... 27777


✅ Average OCR similarity: 0.32
Extracted Text:
 ‘Date; 11/09/22 9404


✅ Average OCR similarity: 0.11
Extracted Text:
 العميل]”


✅ Average OCR similarity: 1.00
Extracted Text:
 For complaints and suggest ions


✅ Average OCR similarity: 0.90
Extracted Text:
 Printed At: 2022/09/18 69:28:29 PM


✅ Average OCR similarity: 0.97
Extracted Text:
 Order Not. 6629212 - 1440


✅ Average OCR similarity: 0.92
Extracted Text:
 9.50 wlo> Xl


✅ Average OCR similarity: 0.38
Extracted Text:


✅ Average OCR similarity: 0.00
Extracted Text:
 0.00
change


✅ Average OCR similarity: 0.00
Extracted Text:
 اا افورة اكياسنفاياك.


✅ Average OCR similarity: 0.06
Extracted Text:
 *GASOLINE 92 1 EGP 440.00


✅ Average OCR similarity: 1.00
Extracted Text:
 20TAB


✅ Average OCR similarity: 1.00
Extracted Text:
  Credi eCard 1 10.0000 1


✅ Average OCR similarity: 0.25
Extracted Text:
 الباقى: ا


✅ Average OCR similarity: 0.27
Extracted Text:
 1070622021


✅ Average OCR similarity: 0.80
Extracted Text:
 المبلغ الكلي: ‎EGP‏ 57.14


✅ Average OCR similarity: 0.00
Extracted Text:
 | بون رقم : 749


✅ Average OCR similarity: 0.38
Extracted Text:
 SubTotal -LE38.00


✅ Average OCR similarity: 0.62
Extracted Text:
 AMOUNT 1٠25138 0


✅ Average OCR similarity: 0.62
Extracted Text:
 Store:106 PoS:1 User: 335


✅ Average OCR similarity: 0.22
Extracted Text:
 إاجمالى العاتورة قبل الخصم ‎W421‏


✅ Average OCR similarity: 0.03
Extracted Text:
 Sub Total 72.00


✅ Average OCR similarity: 1.00

In [ ]:
import pandas as pd

df=pd.DataFrame(data_dict,columns=data_dict.keys())
df.head()

,image path,labled,predicted_tesseract,similarities_tesseract
0,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,SALE,SALE\n,1.000000
1,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,Invoice Date: 30-10-2021,Invoice Date: 30-10-2021\n,1.000000
2,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,40.00 160.00 فرخ حلوانى لنشون 0.250,0 لئنشون حلوائي فرع ;469.90 40.00\n,0.000000
3,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,MasterCard 122.00,eee aan Oe ite\nMasterCard 122.00\n,0.058824
4,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,GROSS: 368,GROSS: 368\n,1.000000

In [ ]:
df.to_csv('/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample/tesseract_OCR.csv')

# ***paddle***

In [ ]:
!pip install paddlepaddle paddleocr

Collecting paddlepaddle
  Downloading paddlepaddle-3.0.0-cp311-cp311-manylinux1_x86_64.whl.metadata (8.9 kB)
Collecting paddleocr
  Downloading paddleocr-2.10.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (0.28.1)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (2.0.2)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (5.29.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (11.2.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (4.4.2)
Collecting astor (from paddlepaddle)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting opt_einsum==3.3.0 (from paddlepaddle)
  Downloading opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (3.4.2)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.11/dist-packages (from paddlepaddle) (4.13.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.11/dist-packages (from paddleocr) (2.1.0)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.11/dist-packages (from paddleocr) (0.25.2)
Collecting pyclipper (from paddleocr)
  Downloading pyclipper-1.3.0.post6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting lmdb (from paddleocr)
  Downloading lmdb-1.6.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from paddleocr) (4.67.1)
Collecting rapidfuzz (from paddleocr)
  Downloading rapidfuzz-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (from paddleocr) (4.11.0.86)
Requirement already satisfied: opencv-contrib-python in /usr/local/lib/python3.11/dist-packages (from paddleocr) (4.11.0.86)
Requirement already satisfied: cython in /usr/local/lib/python3.11/dist-packages (from paddleocr) (3.0.12)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from paddleocr) (6.0.2)
Collecting python-docx (from paddleocr)
  Downloading python_docx-1.1.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from paddleocr) (4.13.4)
Requirement already satisfied: fonttools>=4.24.0 in /usr/local/lib/python3.11/dist-packages (from paddleocr) (4.57.0)
Collecting fire>=0.3.0 (from paddleocr)
  Downloading fire-0.7.0.tar.gz (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from paddleocr) (2.32.3)
Requirement already satisfied: albumentations in /usr/local/lib/python3.11/dist-packages (from paddleocr) (2.0.5)
Requirement already satisfied: albucore in /usr/local/lib/python3.11/dist-packages (from paddleocr) (0.0.23)
Requirement already satisfied: termcolor in /usr/local/lib/python3.11/dist-packages (from fire>=0.3.0->paddleocr) (3.0.1)
Requirement already satisfied: stringzilla>=3.10.4 in /usr/local/lib/python3.11/dist-packages (from albucore->paddleocr) (3.12.5)
Requirement already satisfied: simsimd>=5.9.2 in /usr/local/lib/python3.11/dist-packages (from albucore->paddleocr) (6.2.1)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in /usr/local/lib/python3.11/dist-packages (from albucore->paddleocr) (4.11.0.86)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.11/dist-packages (from albumentations->paddleocr) (1.15.2)
Requirement already satisfied: pydantic>=2.9.2 in /usr/local/lib/python3.11/dist-packages (from albumentations->paddleocr) (2.11.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->paddleocr) (2.7)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->paddlepaddle) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->paddlepaddle) (0.16.0)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from python-docx->paddleocr) (5.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->paddleocr) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->paddleocr) (2.4.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.11/dist-packages (from scikit-image->paddleocr) (2.37.0)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.11/dist-packages (from scikit-image->paddleocr) (2025.3.30)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.11/dist-packages (from scikit-image->paddleocr) (24.2)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.11/dist-packages (from scikit-image->paddleocr) (0.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9.2->albumentations->paddleocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9.2->albumentations->paddleocr) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9.2->albumentations->paddleocr) (0.4.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->paddlepaddle) (1.3.1)
Downloading paddlepaddle-3.0.0-cp311-cp311-manylinux1_x86_64.whl (192.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 MB 9.6 MB/s eta 0:00:00
Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 6.5 MB/s eta 0:00:00
Downloading paddleocr-2.10.0-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 98.2 MB/s eta 0:00:00
Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Downloading lmdb-1.6.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.8/297.8 kB 27.2 MB/s eta 0:00:00
Downloading pyclipper-1.3.0.post6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (969 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 969.6/969.6 kB 59.7 MB/s eta 0:00:00
Downloading python_docx-1.1.2-py3-none-any.whl (244 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 kB 24.4 MB/s eta 0:00:00
Downloading rapidfuzz-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 105.6 MB/s eta 0:00:00
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.7.0-py3-none-any.whl size=114249 sha256=171547fab2a264999ad0b69d7357e6d89dcf83cb8b7ee972577f4c3e9f5ffb03
  Stored in directory: /root/.cache/pip/wheels/46/54/24/1624fd5b8674eb1188623f7e8e17cdf7c0f6c24b609dfb8a89
Successfully built fire
Installing collected packages: pyclipper, lmdb, rapidfuzz, python-docx, opt_einsum, fire, astor, paddlepaddle, paddleocr
  Attempting uninstall: opt_einsum
    Found existing installation: opt_einsum 3.4.0
    Uninstalling opt_einsum-3.4.0:
      Successfully uninstalled opt_einsum-3.4.0
Successfully installed astor-0.8.1 fire-0.7.0 lmdb-1.6.2 opt_einsum-3.3.0 paddleocr-2.10.0 paddlepaddle-3.0.0 pyclipper-1.3.0.post6 python-docx-1.1.2 rapidfuzz-3.13.0

In [ ]:
!wget https://github.com/google/fonts/raw/main/ofl/amiri/Amiri-Regular.ttf -O /root/.paddleocr/arabic-font.ttf

/root/.paddleocr/arabic-font.ttf: No such file or directory

In [ ]:
from paddleocr import PaddleOCR
import re
from collections import defaultdict

import cv2
import numpy as np
from PIL import Image
from google.colab.patches import cv2_imshow
from matplotlib import pyplot as plt
import os
import json
from glob import glob
from difflib import SequenceMatcher

## predict

In [ ]:
base_path='/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample'

In [ ]:
from paddleocr import PaddleOCR
import re
from collections import defaultdict

def paddel_predict(image_path):
    # Initialize PaddleOCR with Arabic support
    ocr = PaddleOCR(use_angle_cls=True, lang='ar')

    # Perform OCR
    result = ocr.ocr(image_path, cls=False)

    # ✅ Handle case when OCR fails or returns nothing
    if not result or not result[0]:
        print(f"[WARNING] No text detected in image: {image_path}")
        return ''

    # Function to check if text is Arabic
    def is_arabic(text):
        return bool(re.search(r'[\u0600-\u06FF]', text))

    # Group text into lines using Y position
    lines_dict = defaultdict(list)
    line_threshold = 15  # pixels to group into same line

    for line in result[0]:
        box = line[0]
        text = line[1][0]
        x_coords = [pt[0] for pt in box]
        y_coords = [pt[1] for pt in box]
        avg_x = sum(x_coords) / 4
        avg_y = sum(y_coords) / 4

        # Assign to a line group based on Y
        line_key = round(avg_y / line_threshold)
        lines_dict[line_key].append({'text': text, 'x': avg_x})

    # Sort lines top-to-bottom
    sorted_lines = sorted(lines_dict.items(), key=lambda x: x[0])

    # Process each line
    final_lines = []
    for _, line_items in sorted_lines:
        # Determine if this line is mostly Arabic
        arabic_count = sum(1 for item in line_items if is_arabic(item['text']))
        is_arabic_line = arabic_count >= len(line_items) / 2

        # Sort by x (LTR or RTL)
        line_items.sort(key=lambda x: -x['x'] if is_arabic_line else x['x'])

        # Reverse Arabic text elements only
        processed_line = [item['text'][::-1] if is_arabic(item['text']) else item['text'] for item in line_items]
        final_lines.append(' '.join(processed_line))

    # Final predicted text (single line output)
    predicted_text = ' '.join(final_lines)
    print(predicted_text)
    return predicted_text

In [ ]:
def get_label_paddel(image_path):
    try:
        ann_path = image_path.replace('.jpg','.txt').replace('img','ann')
        with open(ann_path, 'r') as f:
            lines = f.readline()
            lines=eval(lines)
            result = ' '.join(lines)
            return result
    except FileNotFoundError:
        print(f"File not found: {ann_path}")

In [ ]:
def average_similarity_paddel(ground_truths,perdicted):

    def string_similarity(a, b):
        return SequenceMatcher(None, a, b).ratio()

    # Calculate average similarity
    if perdicted:
        similarities = [string_similarity(pred, gt) for pred, gt in zip(perdicted, ground_truths)]
        average_similarity = sum(similarities) / len(similarities)
        print(f"\n✅ Average OCR similarity: {average_similarity:.2f}")
        return average_similarity
    else:
        print("\n⚠️ No valid predictions made.")
        return -1.0

In [ ]:
predictions = []
data_dict={'image path':[] , 'labled':[],'predicted_tesseract' :[],'similarities_tesseract':[]}

for img in glob(os.path.join(base_path, 'img', '*')):

    results_text=paddel_predict(img)
    data_dict['image path'].append(img)
    data_dict['predicted_tesseract'].append(results_text)
    label=get_label_paddel(img)
    data_dict['labled'].append(label)
    data_dict['similarities_tesseract'].append(average_similarity_paddel(label,results_text))
    predictions.append(results_text)

[2025/05/01 14:37:25] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, use_gcu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/arabic/arabic_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.11/dist-packages/paddleocr/ppocr/utils/dict/arabic_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, onnx_providers=False, onnx_sess_options=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ar', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2025/05/01 14:37:26] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.04762601852416992
[2025/05/01 14:37:26] ppocr DEBUG: rec_res num  : 1, elapsed : 0.05254316329956055
SALE

✅ Average OCR similarity: 1.00
[2025/05/01 14:37:26] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, use_gcu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/arabic/arabic_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.11/dist-packages/paddleocr/ppocr/utils/dict/arabic_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, onnx_providers=False, onnx_sess_options=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ar', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2025/05/01 14:37:27] ppocr DEBUG: dt_boxes num : 3, elapsed : 0.04788327217102051
[2025/05/01 14:37:27] ppocr DEBUG: rec_res num  : 3, elapsed : 0.10704159736633301
Invoice Date: 30-10-2021

✅ Average OCR similarity: 1.00
[2025/05/01 14:37:28] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, use_gcu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/arabic/arabic_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.11/dist-packages/paddleocr/ppocr/utils/dict/arabic_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, onnx_providers=False, onnx_sess_options=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ar', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2025/05/01 14:37:29] ppocr DEBUG: dt_boxes num : 7, elapsed : 0.09850955009460449
[2025/05/01 14:37:29] ppocr DEBUG: rec_res num  : 7, elapsed : 0.4920663833618164
0.250 لنشون حلوائيفرغ 6٥ 0 40

✅ Average OCR similarity: 0.07
[2025/05/01 14:37:29] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, use_gcu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/arabic/arabic_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.11/dist-packages/paddleocr/ppocr/utils/dict/arabic_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, onnx_providers=False, onnx_sess_options=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ar', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2025/05/01 14:37:31] ppocr DEBUG: dt_boxes num : 3, elapsed : 0.02935314178466797
[2025/05/01 14:37:31] ppocr DEBUG: rec_res num  : 3, elapsed : 0.1729590892791748
MasterCard 22

✅ Average OCR similarity: 0.92
[2025/05/01 14:37:31] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, use_gcu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/arabic/arabic_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.11/dist-packages/paddleocr/ppocr/utils/dict/arabic_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, onnx_providers=False, onnx_sess_options=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ar', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2025/05/01 14:37:33] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.05276775360107422
[2025/05/01 14:37:33] ppocr DEBUG: rec_res num  : 2, elapsed : 0.11765551567077637
GROSS: 368

✅ Average OCR similarity: 1.00
[2025/05/01 14:37:33] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, use_mlu=False, use_gcu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ml/Multilingual_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/arabic/arabic_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.11/dist-packages/paddleocr/ppocr/utils/dict/arabic_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, onnx_providers=False, onnx_sess_options=False, return_word_box=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, formula_algorithm='LaTeXOCR', formula_model_dir=None, formula_char_dict_path=None, formula_batch_num=1, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, formula=False, ocr=True, recovery=False, recovery_to_markdown=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ar', det=True, rec=True, type='ocr', savefile=False, ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[2025/05/01 14:37:34] ppocr DEBUG: dt_boxes num : 2, elapsed : 0.05652046203613281
[2025/05/01 14:37:34] ppocr DEBUG: rec_res num  : 2, elapsed : 0.08061528205871582
RNED DE

✅ Average OCR similarity: 1.00

## csv file

In [ ]:
import pandas as pd

df=pd.DataFrame(data_dict,columns=data_dict.keys())
df.head()

,image path,labled,predicted_tesseract,similarities_tesseract
0,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,SALE,SALE,1.000000
1,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,Invoice Date: 30-10-2021,Invoice Date: 30-10-2021,1.000000
2,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,40.00 160.00 فرخ حلوانى لنشون 0.250,0.250 لنشون حلوائيفرغ 6٥ 0 40,0.068966
3,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,MasterCard 122.00,MasterCard 22,0.923077
4,/content/drive/MyDrive/DEPI_Project_Dataset/MI...,GROSS: 368,GROSS: 368,1.000000

In [ ]:
df.to_csv('/content/drive/MyDrive/DEPI_Project_Dataset/MIX_Data_Sample/paddle_OCR.csv')